name: countly_flutter_np
description: Countly is an innovative, real-time, open source mobile analytics. This plugin is a flavour of the SDK without push notifications.

version: 24.4.1
homepage: https://support.count.ly/hc/en-us/articles/360037944212-Flutter
repository: https://github.com/Countly/countly-sdk-flutter-bridge
issue_tracker: https://github.com/Countly/countly-sdk-flutter-bridge/issues
documentation: https://support.count.ly/hc/en-us/articles/360037944212
platforms:
  android:
  ios:

environment:
    sdk: ">=2.12.0 <3.0.0"
    flutter: ">=2.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_plugin_android_lifecycle: ^2.0.2
    pedantic: ^1.11.0

dev_dependencies:
    flutter_lints: ^2.0.1
    flutter_test:
        sdk: flutter
    integration_test:
        sdk: flutter

flutter:
    plugin:
        platforms:
            android:
                package: ly.count.dart.countly_flutter
                pluginClass: CountlyFlutterPlugin
            ios:
                pluginClass: CountlyFlutterPlugin
